/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    membres: MembreAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    membres: Membre;
    profils: Profil;
    'photos-profil': PhotosProfil;
    justificatifs: Justificatif;
    media: Media;
    actualites: Actualite;
    evenements: Evenement;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    membres: MembresSelect<false> | MembresSelect<true>;
    profils: ProfilsSelect<false> | ProfilsSelect<true>;
    'photos-profil': PhotosProfilSelect<false> | PhotosProfilSelect<true>;
    justificatifs: JustificatifsSelect<false> | JustificatifsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    actualites: ActualitesSelect<false> | ActualitesSelect<true>;
    evenements: EvenementsSelect<false> | EvenementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'en-tete': EnTete;
    'pied-de-page': PiedDePage;
    parametres: Parametre;
    'page-association': PageAssociation;
    'pages-ipest': PagesIpest;
  };
  globalsSelect: {
    'en-tete': EnTeteSelect<false> | EnTeteSelect<true>;
    'pied-de-page': PiedDePageSelect<false> | PiedDePageSelect<true>;
    parametres: ParametresSelect<false> | ParametresSelect<true>;
    'page-association': PageAssociationSelect<false> | PageAssociationSelect<true>;
    'pages-ipest': PagesIpestSelect<false> | PagesIpestSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | Membre;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MembreAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  nomComplet: string;
  role: 'superadmin' | 'admin';
  /**
   * Ex. Président, Responsable communication…
   */
  poste?: string | null;
  /**
   * Décocher en fin de mandat pour couper l’accès sans supprimer l’historique.
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membres".
 */
export interface Membre {
  id: number;
  prenom: string;
  nom: string;
  anneeSortie: number;
  dateNaissance: string;
  emailVerifie?: boolean | null;
  inscriptionTerminee?: boolean | null;
  etapeProfilFaite?: boolean | null;
  compteStatut?: ('actif' | 'suspendu') | null;
  verification: {
    methode?: ('institutionnelle' | 'justificatif') | null;
    /**
     * Passer à « Vérifié » ou « Refusé » envoie automatiquement un e-mail au membre.
     */
    statut: 'non_verifie' | 'en_attente' | 'verifie' | 'refuse';
    adresseInstitutionnelle?: string | null;
    justificatifTexte?: string | null;
    justificatif?: (number | null) | Justificatif;
    motifRefus?: string | null;
    dateValidation?: string | null;
  };
  codeEmail?: {
    hash?: string | null;
    expire?: string | null;
    tentatives?: number | null;
    envoyeLe?: string | null;
  };
  codeIpest?: {
    hash?: string | null;
    expire?: string | null;
    tentatives?: number | null;
    envoyeLe?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'membres';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "justificatifs".
 */
export interface Justificatif {
  id: number;
  membre?: (number | null) | Membre;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profils".
 */
export interface Profil {
  id: number;
  membre: number | Membre;
  nomAffiche?: string | null;
  photo?: (number | null) | PhotosProfil;
  whatsapp?: string | null;
  emailContact?: string | null;
  linkedin?: string | null;
  ecole?: string | null;
  promotionEcole?: number | null;
  posteActuel?: string | null;
  secteur?:
    | (
        | 'Ingénierie et industrie'
        | 'Informatique et logiciel'
        | 'Data et intelligence artificielle'
        | 'Finance et assurance'
        | 'Conseil'
        | 'Recherche et enseignement'
        | 'Énergie et environnement'
        | 'Télécommunications'
        | 'Santé'
        | 'Entrepreneuriat'
        | 'Secteur public'
        | 'Études en cours'
        | 'Autre'
      )
    | null;
  localisation?: string | null;
  /**
   * Servent de critère de recherche dans l’annuaire.
   */
  entreprises?: string[] | null;
  disponibilite?: ('tres_ouvert' | 'ouvert' | 'peu_ouvert') | null;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos-profil".
 */
export interface PhotosProfil {
  id: number;
  proprietaire?: (number | null) | Membre;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Lue par les lecteurs d’écran et utile au référencement.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    vignette?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    carte?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Chaque actualité apparaît dans le carrousel de la page d’accueil pendant 15 jours après sa date de publication.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites".
 */
export interface Actualite {
  id: number;
  titre: string;
  datePublication: string;
  image?: (number | null) | Media;
  /**
   * 320 caractères maximum, affichés dans le carrousel.
   */
  resume: string;
  /**
   * Adresse d’une page du site (/activites) ou d’un site externe.
   */
  lien?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements".
 */
export interface Evenement {
  id: number;
  nom: string;
  dateDebut: string;
  dateFin?: string | null;
  enLigne?: boolean | null;
  lieu?: string | null;
  lienVisio?: string | null;
  /**
   * Affichée sur la carte de l’événement (280 caractères maximum).
   */
  description: string;
  prix: 'gratuit' | 'payant';
  montant?: string | null;
  public: 'tout_public' | 'ipestiens_alumni' | 'ipestiens' | 'alumni';
  lienInscription?: string | null;
  photo?: (number | null) | Media;
  contenu?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Photos affichées sur la page détaillée, par exemple après l’événement.
   */
  galerie?: (number | Media)[] | null;
  finEffective?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'membres';
        value: number | Membre;
      } | null)
    | ({
        relationTo: 'profils';
        value: number | Profil;
      } | null)
    | ({
        relationTo: 'photos-profil';
        value: number | PhotosProfil;
      } | null)
    | ({
        relationTo: 'justificatifs';
        value: number | Justificatif;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'actualites';
        value: number | Actualite;
      } | null)
    | ({
        relationTo: 'evenements';
        value: number | Evenement;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'membres';
        value: number | Membre;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'membres';
        value: number | Membre;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  nomComplet?: T;
  role?: T;
  poste?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membres_select".
 */
export interface MembresSelect<T extends boolean = true> {
  prenom?: T;
  nom?: T;
  anneeSortie?: T;
  dateNaissance?: T;
  emailVerifie?: T;
  inscriptionTerminee?: T;
  etapeProfilFaite?: T;
  compteStatut?: T;
  verification?:
    | T
    | {
        methode?: T;
        statut?: T;
        adresseInstitutionnelle?: T;
        justificatifTexte?: T;
        justificatif?: T;
        motifRefus?: T;
        dateValidation?: T;
      };
  codeEmail?:
    | T
    | {
        hash?: T;
        expire?: T;
        tentatives?: T;
        envoyeLe?: T;
      };
  codeIpest?:
    | T
    | {
        hash?: T;
        expire?: T;
        tentatives?: T;
        envoyeLe?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profils_select".
 */
export interface ProfilsSelect<T extends boolean = true> {
  membre?: T;
  nomAffiche?: T;
  photo?: T;
  whatsapp?: T;
  emailContact?: T;
  linkedin?: T;
  ecole?: T;
  promotionEcole?: T;
  posteActuel?: T;
  secteur?: T;
  localisation?: T;
  entreprises?: T;
  disponibilite?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos-profil_select".
 */
export interface PhotosProfilSelect<T extends boolean = true> {
  proprietaire?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        avatar?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "justificatifs_select".
 */
export interface JustificatifsSelect<T extends boolean = true> {
  membre?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        vignette?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        carte?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites_select".
 */
export interface ActualitesSelect<T extends boolean = true> {
  titre?: T;
  datePublication?: T;
  image?: T;
  resume?: T;
  lien?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements_select".
 */
export interface EvenementsSelect<T extends boolean = true> {
  nom?: T;
  dateDebut?: T;
  dateFin?: T;
  enLigne?: T;
  lieu?: T;
  lienVisio?: T;
  description?: T;
  prix?: T;
  montant?: T;
  public?: T;
  lienInscription?: T;
  photo?: T;
  contenu?: T;
  galerie?: T;
  finEffective?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "en-tete".
 */
export interface EnTete {
  id: number;
  /**
   * Version monochrome blanche, affichée sur fond sombre.
   */
  logoBlanc?: (number | null) | Media;
  imageDeFond?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pied-de-page".
 */
export interface PiedDePage {
  id: number;
  accroche?: string | null;
  emailContact?: string | null;
  telephone?: string | null;
  liensInformations?:
    | {
        libelle: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  reseauxSociaux?:
    | {
        plateforme: 'facebook' | 'linkedin' | 'instagram' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * L’année en cours est ajoutée automatiquement devant.
   */
  mentionCopyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres".
 */
export interface Parametre {
  id: number;
  /**
   * Page de paiement de la cotisation (plateforme à définir).
   */
  lienCotisation?: string | null;
  lienDon?: string | null;
  lienWhatsApp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-association".
 */
export interface PageAssociation {
  id: number;
  quiSommesNous?: {
    titre?: string | null;
    texte?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    photo?: (number | null) | Media;
  };
  pourquoiAdherer?: {
    texte?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    cotisation?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  equipe?: {
    /**
     * L’ordre de la liste est l’ordre d’affichage. Glisser-déposer pour réordonner.
     */
    membres?:
      | {
          prenom: string;
          nom: string;
          poste: string;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-ipest".
 */
export interface PagesIpest {
  id: number;
  presentation?: {
    texte?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    photo?: (number | null) | Media;
  };
  histoire?: {
    introduction?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    blocs?:
      | {
          titre?: string | null;
          texte?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          photo?: (number | null) | Media;
          legende?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  campus?: {
    introduction?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    blocs?:
      | {
          titre?: string | null;
          texte?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          photo?: (number | null) | Media;
          legende?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  admission?: {
    banniere?: (number | null) | Media;
    texte?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Une ligne par année. À mettre à jour chaque année.
     */
    statistiques?:
      | {
          annee: number;
          mpsiPremier?: number | null;
          mpsiDernier?: number | null;
          pcsiPremier?: number | null;
          pcsiDernier?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  cursus?: {
    texte?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    capacites?:
      | {
          filiere: string;
          capacite: string;
          id?: string | null;
        }[]
      | null;
    volumesHoraires?:
      | {
          matiere: string;
          mpsi?: string | null;
          pcsi?: string | null;
          mp?: string | null;
          psi?: string | null;
          pc?: string | null;
          id?: string | null;
        }[]
      | null;
    concours?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  concours?: {
    introduction?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    liste?:
      | {
          nom: string;
          url: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  apresIpest?: {
    introduction?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Les écoles sont regroupées par concours sur la page.
     */
    ecoles?:
      | {
          nom: string;
          /**
           * Ex. X-ENS, Mines-Ponts, Centrale-Supélec, CCINP…
           */
          concours: string;
          url?: string | null;
          boursiere?: boolean | null;
          id?: string | null;
        }[]
      | null;
    lienListeBoursieres?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "en-tete_select".
 */
export interface EnTeteSelect<T extends boolean = true> {
  logoBlanc?: T;
  imageDeFond?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pied-de-page_select".
 */
export interface PiedDePageSelect<T extends boolean = true> {
  accroche?: T;
  emailContact?: T;
  telephone?: T;
  liensInformations?:
    | T
    | {
        libelle?: T;
        url?: T;
        id?: T;
      };
  reseauxSociaux?:
    | T
    | {
        plateforme?: T;
        url?: T;
        id?: T;
      };
  mentionCopyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres_select".
 */
export interface ParametresSelect<T extends boolean = true> {
  lienCotisation?: T;
  lienDon?: T;
  lienWhatsApp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-association_select".
 */
export interface PageAssociationSelect<T extends boolean = true> {
  quiSommesNous?:
    | T
    | {
        titre?: T;
        texte?: T;
        photo?: T;
      };
  pourquoiAdherer?:
    | T
    | {
        texte?: T;
        cotisation?: T;
      };
  equipe?:
    | T
    | {
        membres?:
          | T
          | {
              prenom?: T;
              nom?: T;
              poste?: T;
              photo?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-ipest_select".
 */
export interface PagesIpestSelect<T extends boolean = true> {
  presentation?:
    | T
    | {
        texte?: T;
        photo?: T;
      };
  histoire?:
    | T
    | {
        introduction?: T;
        blocs?:
          | T
          | {
              titre?: T;
              texte?: T;
              photo?: T;
              legende?: T;
              id?: T;
            };
      };
  campus?:
    | T
    | {
        introduction?: T;
        blocs?:
          | T
          | {
              titre?: T;
              texte?: T;
              photo?: T;
              legende?: T;
              id?: T;
            };
      };
  admission?:
    | T
    | {
        banniere?: T;
        texte?: T;
        statistiques?:
          | T
          | {
              annee?: T;
              mpsiPremier?: T;
              mpsiDernier?: T;
              pcsiPremier?: T;
              pcsiDernier?: T;
              id?: T;
            };
      };
  cursus?:
    | T
    | {
        texte?: T;
        capacites?:
          | T
          | {
              filiere?: T;
              capacite?: T;
              id?: T;
            };
        volumesHoraires?:
          | T
          | {
              matiere?: T;
              mpsi?: T;
              pcsi?: T;
              mp?: T;
              psi?: T;
              pc?: T;
              id?: T;
            };
        concours?: T;
      };
  concours?:
    | T
    | {
        introduction?: T;
        liste?:
          | T
          | {
              nom?: T;
              url?: T;
              description?: T;
              id?: T;
            };
      };
  apresIpest?:
    | T
    | {
        introduction?: T;
        ecoles?:
          | T
          | {
              nom?: T;
              concours?: T;
              url?: T;
              boursiere?: T;
              id?: T;
            };
        lienListeBoursieres?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}